name: Send Test Summary to Discord

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 9 * * *'   # Daily at 9:00 AM UTC
    - cron: '0 16 * * *'  # Daily at 4:00 PM UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  test-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: |
          npm test || true
          # Check if test-results.json exists and is valid JSON
          if [ -f test-results.json ]; then
            # Try to parse the JSON, if it fails, create a default one
            node -e "try { JSON.parse(require('fs').readFileSync('test-results.json', 'utf8')) } catch(e) { console.log('Invalid JSON, creating default'); require('fs').writeFileSync('test-results.json', JSON.stringify({stats:{tests:0,passes:0,failures:0,pending:0,duration:0},tests:[],failures:[]})) }"
          else
            # Create default test results if file doesn't exist
            echo '{"stats":{"tests":0,"passes":0,"failures":0,"pending":0,"duration":0},"tests":[],"failures":[]}' > test-results.json
          fi
        continue-on-error: true

      - name: Generate Test Summary
        run: node scripts/parse-test-summary.js

      - name: Send Report to Discord
        run: node scripts/send-discord-report.js
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1401862123520397445/jvU92hE5VNYI84DW1mtnRvC6pF-r_bji7KeBVA4lD1Z_9JDKGrxEpdlSO18rXyDLjg3O